version: '3.8'

services:
  apodworker:
    image:  apodworker
    container_name: apod-worker
    environment:
      SERVICE_APODKEY: rj9LSQPmAWkFpF7WHwiyBoe2s0smefB3geveOnWI
      SERVICE_DATAPATH: data
      SERVICE_SERVER_ADDRESS: localhost:8080
    ports:
      - "8080:8080"
      
  postgres:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
